# -*- coding: utf-8 -*-
"""Lab01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zkPZRpJ8L2bSZCaMaPWPOdSn37IPHgW
"""

pip install ucimlrepo

"""# **Data Load**"""

from ucimlrepo import fetch_ucirepo

# fetch dataset
mushroom = fetch_ucirepo(id=73)

# data (as pandas dataframes)
X = mushroom.data.features
y = mushroom.data.targets

# metadata
print(mushroom.metadata)

# variable information
print(mushroom.variables)

"""# **Exploratory Data Analysis (EDA)**"""

print("Missing values in 'stalk-root' column:")
print(X['stalk-root'].value_counts())

print("\nDistribution of categorical features in X:")
for col in X.columns:
    print(f"\nColumn: {col}")
    print(X[col].value_counts())

print("\nDistribution of target variable y:")
print(y.value_counts())

"""# **Preprocess Data**"""

import numpy as np

# Instruction 1: Identify and count missing values (NaN) in 'stalk-root'
print("Number of NaN values in 'stalk-root' column:", X['stalk-root'].isnull().sum())

# Instruction 2: Replace missing values (NaN) with the mode of 'stalk-root'
mode_stalk_root = X['stalk-root'].mode()[0]
X['stalk-root'].fillna(mode_stalk_root, inplace=True)
print("\nAfter filling NaN values in 'stalk-root':")
print(X['stalk-root'].value_counts())

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# Instruction 4: Create a ColumnTransformer for OneHotEncoder
# Get all column names from X as they are all categorical
categorical_features = X.columns
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

# Instruction 5: Fit and transform X using the preprocessor
X_encoded = preprocessor.fit_transform(X)

# Instruction 7: Instantiate a LabelEncoder object and fit it to y
label_encoder = LabelEncoder()

# Instruction 8: Transform y using the fitted LabelEncoder
y_encoded = label_encoder.fit_transform(y.squeeze()) # .squeeze() to convert DataFrame to Series for LabelEncoder

# Instruction 10: Split the X_encoded and y_encoded into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=42
)

print("Data preprocessing complete.")
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""# **Decision Tree**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instantiate a DecisionTreeClassifier object
dt_classifier = DecisionTreeClassifier(random_state=42)

# Train the Decision Tree Classifier
dt_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_dt = dt_classifier.predict(X_test)

# Calculate and print the accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Classifier Accuracy: {accuracy_dt:.4f}")

# Print the classification report
print("\nDecision Tree Classifier Classification Report:")
print(classification_report(y_test, y_pred_dt))

# Print the confusion matrix
print("\nDecision Tree Classifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

"""# **Random forest**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define a list of n_estimators values to test
n_estimators_values = [1, 50, 100, 150, 200, 250]

# Initialize a dictionary to store accuracy results
rf_accuracies = {}

print("Random Forest Classifier Accuracies with varying n_estimators:")
for n_estimators in n_estimators_values:
    # Instantiate a RandomForestClassifier object
    rf_classifier = RandomForestClassifier(n_estimators=n_estimators, random_state=42)

    # Train the Random Forest Classifier
    rf_classifier.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred_rf = rf_classifier.predict(X_test)

    # Calculate the accuracy score
    accuracy_rf = accuracy_score(y_test, y_pred_rf)

    # Store the accuracy
    rf_accuracies[n_estimators] = accuracy_rf

    # Print the accuracy for the current n_estimators value
    print(f"  n_estimators={n_estimators}: Accuracy = {accuracy_rf:.4f}")

"""# **Model Comparison**"""

print("\n--- Model Performance Comparison ---")
print(f"Decision Tree Classifier Accuracy: {accuracy_dt:.4f}")

print("\nRandom Forest Classifier Accuracies:")
for n_estimators, accuracy in rf_accuracies.items():
    print(f"  n_estimators={n_estimators}: Accuracy = {accuracy:.4f}")